version: '3'
services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8001:80"

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "8002:80"

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8003:80"

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:80"